[package]
name = "cdir_python"
version = "0.1.0"
edition = "2018"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cdir-core = { path = "../core" }
pyo3 = { version = "0.13.2", features = ["extension-module"] }
